### ISSUE TITLE
It's possible to set crop boundaries outside of the image, causing jpegtran error

### ISSUE THREAD

**Issue by dreamlayers** [jepler/cropgui#100]
In both cropgui.py and cropgtk.py, I am able to move the crop boundary beyond the edges of the image. This means I'm making the "crop area" larger than the image. For example, drag the top left corner of the crop area further up and to the left. That results in an error like `jpegtran: bogus -crop argument '6224fx3660f+-912+-672'` and no cropped image being produced. Note the negative arguments, supplied as `+-`. Going beyond the bottom results in an output image with a grey area there, and going beyond the right side results in the rightmost pixels being continued into the expanded area.

I don't want any of this to happen. Instead, I want the crop area to be constrained to the image. Sometimes I want to crop the image in some directions, but leave one or more edges uncropped. The ability to move the boundaries outside the image complicates such a task.

**Comment by howff** [comment]
I fixed this elsewhere but haven't fed the changes back yet. The fix was quite simple as I recall.

**Comment by tdehaeze** [comment]
Very interested by such feature as well.
It is now quite difficult just to reduce the vertical size without affecting the horizontal one.

**Comment by howff** [comment]
See pull request #104

**Comment by tdehaeze** [comment]
Thanks. Hopefully it will be merged soon.

**Comment by dreamlayers** [comment]
This has been merged and I confirm that the problem has been fixed. Closing the issue because of that.
