### ISSUE TITLE
Cannot include the last row and column of the image

### ISSUE THREAD

**Issue by pepalogik** [jepler/cropgui#106]
Initially the whole image is selected, but when I start changing the selection, Right and Bottom decrease by 1 and cannot be set to include the whole image again. This seems to happen with every image.

Cloned today and installed with `./install.sh -f gtk -u -P /usr/bin/python3`.

**Comment by Maxr1998** [comment]
THis is caused by the unnecessary `-1` in e0e8566ec0e53f596bd8935a00d3b981a13f70de. Should be an easy fix.
