### ISSUE TITLE
cropgui will happily open non-JPEG images

### ISSUE THREAD

**Issue by za3k** [jepler/cropgui#12]
`cropgui cats.png` will quite happily open, show, and let you prepare to crop a PNG image, save, and write garbage to `cats-crop.jpg`, all while showing an error only on stderr.

Seems easy to guard against.

**Comment by onno74** [comment]
cropgtk can now crop non jpeg files. There is a pull request that adds this functionality to cropgui.py, too. So I think this issue can be closed.
