### ISSUE TITLE
python/python2

### ISSUE THREAD

**Issue by rafaqz** [jepler/cropgui#17]
Thanks for writing this, its perfect for my needs - quickly cropping and rotating linked images in a markdown writing setup.

I'm just wondering if there a reason #!/usr/bin/python is used everywhere instead of specifying #!/usr/bin/python2?

Running ./cropgtk.py on arch linux (and sooner or later other places) is going to give a syntax error as python links to python3. 

Would it be possible to use python2 explicitly?

**Comment by jepler** [comment]
I did a quick survey and even ancient systems (I have a redhat9 system handy to check:) do have /usr/bin/python2 so yes I'd take a pull request changing this.
