### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by Vaelatern** [jepler/cropgui#25]
The last tagged release was in 2009.
Thank you!

**Comment by logological** [comment]
I'd like to package cropgui for openSUSE but it would be more convenient if a newer release were made.

**Comment by Vaelatern** [comment]
At present, my distribution will not accept a package of cropgui unless it's the latest tagged release. Please do tag a release so modern code can be packaged.

**Comment by jepler** [comment]
I've tagged v0.3.
