### ISSUE TITLE
Should consider IMCU size

### ISSUE THREAD

**Issue by onno74** [jepler/cropgui#31]
Currently, cropgui changes size and position of the region to crop in steps of 8 pixels. This is because lossless cropping is only possible at multiplies of the IMCU size, which is often 8.
However, other values of the IMCU size do occur. At least 16 is also common, maybe others too.
Cropgui should read the IMCU size and use it instead of the fixed value 8 (round in DragManagerBase).

Unfortunately I could not find out how to read IMCU size from a JPEG.

**Comment by za3k** [comment]
en.wikipedia.org/wiki/JPEG. It says "After subsampling, each channel must be split into 8×8 blocks. Depending on chroma subsampling, this yields (Minimum Coded Unit) MCU blocks of size 8×8 (4:4:4 – no subsampling), 16×8 (4:2:2), or most commonly 16×16 (4:2:0)." (via http://www.imagemagick.org/discourse-server/viewtopic.php?t=23162)

I'm having a bit of a time figuring out whether "iMCU" and "MCU" are different, but I can't get ahold of a copy of the JPEG standard, which would make this a lot easier.

Here's how you check that in imagemagick: http://www.imagemagick.org/discourse-server/viewtopic.php?t=17145
I don't know how with your libraries.

**Comment by xiota** [comment]
Is there any real need for this?  `jpegtran` already considers iMCU when it does the actual cropping.  Perhaps this issue can be closed?
