### ISSUE TITLE
Don't lowercase filenames if possible

### ISSUE THREAD

**Issue by logological** [jepler/cropgui#39]
According to the README, cropgui's "output filename is chosen automatically".  The general algorithm seems to be "lowercase the basename, add `-crop` to it, and then add the original suffix".  So if you run cropgui on `FOO.JPG`, then output is `foo-crop.JPG`.

I find the decision to lowercase the basename rather baffling.  Why not leave the basename as-is?

**Comment by jepler** [comment]
I suspect I intended to lowercase the whole thing or maybe just the extension but got it wrong. I'll consider pull requests to change the status quo.

**Comment by arcmags** [comment]
Fixed with [#40](https://github.com/jepler/cropgui/pull/40).

**Comment by jepler** [comment]
Thanks @Arcmags
