### ISSUE TITLE
Won't build on stretch (Debian 9)

### ISSUE THREAD

**Issue by ConradHughes** [jepler/cropgui#43]
Two problems building on stretch:

1. depends on python-support (not in stretch) and
2. has a debian/compat of 4 (no longer supported by stretch).

Workaround for the time being:

1. running debuild -d (ignore dependencies) and
2. change debian/compat to 5 (unsure of the full implications of this).

**Comment by jepler** [comment]
Hi, I'd be happy to merge a pull-request for this.  For my own needs, I would like the package to remain buildable and installable on wheezy.  As dh-python is available in wheezy-backports, requiring it is just fine.

For the consequences of increasing debian/compat, see `man debhelper`.  Wheezy's newest debhelper compatibility version is 9.  I don't think any of the compatibility notes are going to be troublesome for cropgui.

**Comment by ConradHughes** [comment]
Sorry for not responding, and thanks both of you.
