### ISSUE TITLE
Feature Wish: Cropping, without resetting crop-selection to full image size

### ISSUE THREAD

**Issue by klartext** [jepler/cropgui#59]
There should be a way to crop, without resetting the crop-selection to full image-size.
This would be helpful, when many images would needed to be cropped at the same position.
(For screenshots, where certain areas should be cropped, this would be very helpful.)

I think the easiest way to have this is with a second crop-button (instead of key-binding).
YMMV.

**Comment by howff** [comment]
I've got some changes to implement this, shall I submit them as a pull request?

**Comment by ConradHughes** [comment]
I'm marking this closed, with grateful thanks to @howff for the PR.
