### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by muralikodali** [jepler/cropgui#62]
installation is giving following error on ubuntu 18.04 : 
Installing gtk version of cropgui
*** Failed to import cropgui_common.py
    You must add /usr/lib/python2.7/dist-packages to PYTHONPATH

**Comment by brainthinks** [comment]
I had to run `pip2 install Pillow` to get this to work.  Seems that this project uses python2 rather than 3, and that `Pillow` is a required Python dependency.

**Comment by linguisticturn** [comment]
On kubuntu  20.04 LTS (Focal Fossa), at least, though it's likely the same on other flavors of ubuntu, the installation command should read

sudo bash ./install.sh -p /usr -P /usr/bin/python3

Note that it is 'python3', not 'python'.

Until that was changed, the installation script kept generating the following error:

Installing gtk version of cropgui
*** Failed to import cropgui_common.py
    You must add /usr/lib/python3/dist-packages to PYTHONPATH

**Comment by muralikodali** [comment]
I have installed successfully with following command in ubuntu 20.04 : 

sudo bash ./install.sh -p /usr -P /usr/bin/python3
