### ISSUE TITLE
make python3 release

### ISSUE THREAD

**Issue by hannob** [jepler/cropgui#63]
Given the upcoming python2 deprecation it'd be nice to have a release of cropgui supporting python 3.
I saw that changes have been merged to make it python3-compatible, but there's no release yet with these changes.

**Comment by waptaff** [comment]
gentoo is phasing out python2 and without a python3 release, cropgui gets removed.  That's unfortunate.  Is there anything missing for a proper python3 release? https://bugs.gentoo.org/708098

**Comment by jepler** [comment]
You talked me into it.  See: https://github.com/jepler/cropgui/releases/tag/v0.4
