### ISSUE TITLE
cropgui 0.4 cropping wrong area

### ISSUE THREAD

**Issue by hannob** [jepler/cropgui#66]
I have recently updated to the python3/0.4 version of cropgui and it seems to me something is broken, it's not cropping the area that I see on the GUI.

I'm attaching 2 images that show this, 1st is the GUI, which you can see is clearly around a black rectangle on the image:
![screenshot-cropgui](https://user-images.githubusercontent.com/990588/76141282-03342800-6063-11ea-8fa7-0441ec2b60bd.png)

So I'd expect a black rectangle with some white around it. But what I get is only the upper left corner of what I expect:
![x-crop](https://user-images.githubusercontent.com/990588/76141292-121ada80-6063-11ea-9a81-ccb2f6ef7a67.jpg)

**Comment by waptaff** [comment]
Odds are this problem is fixed by https://github.com/jepler/cropgui/pull/65
