### ISSUE TITLE
Does not crop to the correct area

### ISSUE THREAD

**Issue by howff** [jepler/cropgui#77]
The cropped file is not the same area selected in the GUI.
I noticed that the initial crop rectangle is actually larger than the window and is partially off-screen so all crop coordinates will be wrong.
I think the fix is this: use `//` instead of `/` in both files which do this:
```
        drag.scale = max (drag.scale, (drag.w-1)//max_w+1)
        drag.scale = max (drag.scale, (drag.h-1)//max_h+1)
        thumbnail.thumbnail((drag.w//drag.scale, drag.h//drag.scale))
```
Is that a correct deduction and solution?
Would you like a pull request for this?

**Comment by jepler** [comment]
That seems like a reasonable guess, since before the python2 conversion, "int / int" did floor division.  I don't really use/develop cropgui much these days, but I do try to merge PRs that look like they are probably right.
