### ISSUE TITLE
You must add /usr/lib/python3/dist-packages to PYTHONPATH

### ISSUE THREAD

**Issue by leninberg** [jepler/cropgui#80]
Hi!

I am finding some trouble when installing this.
after
`sudo bash ./install.sh -p /usr -P /usr/bin/python`
i get this error
`Installing gtk version of cropgui
*** Failed to import cropgui_common.py
    You must add /usr/lib/python3/dist-packages to PYTHONPATH`

I have tried this
`export PYTHONPATH=${PYTHONPATH}:"/usr/lib/python3/dist-packages"`
but same error.

I am not an expert user of linux so really don't know what to do next.
Thank you.

**Comment by leninberg** [comment]
I have followed the instructions from another user here and it worked
`sudo apt install -y python-tk`
`sudo apt install -y python-pil`
`sudo apt install -y python-imaging-tk`
`sudo apt install -y libjpeg-progs`
`sudo apt install -y libimage-exiftool-perl`
`sudo apt install -y python3.8-distutils`
`git clone https://github.com/jepler/cropgui.git`
`cd (to the cloned folder)`
`sudo bash ./install.sh -p /usr -P /usr/bin/python3`

and to execute
`python3 cropgtk.py`

**Comment by logological** [comment]
IMHO this issue could/should be reopened.  The real issue here is that the error message is not appropriate to the problem (i.e., a missing dependency).

**Comment by 4L3XK** [comment]
On Debian 11 installing little helper package worked fine for me:
```$ sudo apt install python-is-python3```

```
(…)
 This is a convenience package which ships a symlink to point
 the /usr/bin/python interpreter at the current default python3. It may
 improve compatibility with other modern systems, whilst breaking some
 obsolete or 3rd-party software.
(…)
```

**Comment by jepler** [comment]
I'm closing this up because it seems like this was a python2 vs python3 problem. by now most distros have resolved this by removing python2 entirely.
