### ISSUE TITLE
Nothing is saved on Linux Mint (Gtk)

### ISSUE THREAD

**Issue by vipzerix** [jepler/cropgui#97]
CropGUI worked properly when I used it on Manjaro KDE, but it doesn't on Linux Mint Xfce. When I click crop, the application closes and the cropped image is nowhere to be found. I've tried rebooting, setting the "Working Directory" of the application to Pictures, nothing seems to work.

**Comment by jepler** [comment]
I'm not sure what's happening, though I think it's likely to be something with how each system is set up. This could happen for instance if all supporting programs are not installed. Run cropgui or cropgtk from the terminal and check for any errors.

**Comment by vipzerix** [comment]
I deeply apologize for not updating this thread, I managed to make it work after installing certain dependencies through the terminal. Unfortunately, I don't remember details since it's been a year and a quarter since this was posted.
